package com.hdsoft.coremailbridge.model;

import java.util.Date;

public class Mail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coremailbridge_mail.id
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coremailbridge_mail.mid
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    private String mid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coremailbridge_mail.msid
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    private String msid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coremailbridge_mail.fid
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    private String fid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coremailbridge_mail.flag
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    private String flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coremailbridge_mail.mail_from
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    private String mailFrom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coremailbridge_mail.mail_to
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    private String mailTo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coremailbridge_mail.size
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    private String size;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coremailbridge_mail.date
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    private String date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coremailbridge_mail.pushed
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    private Boolean pushed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coremailbridge_mail.pushed_time
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    private Date pushedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coremailbridge_mail.receriver_id
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    private String receriverId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coremailbridge_mail.msg_id
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    private String msgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coremailbridge_mail.create_time
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coremailbridge_mail.update_time
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coremailbridge_mail.subject
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    private String subject;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coremailbridge_mail.id
     *
     * @return the value of coremailbridge_mail.id
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coremailbridge_mail.id
     *
     * @param id the value for coremailbridge_mail.id
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coremailbridge_mail.mid
     *
     * @return the value of coremailbridge_mail.mid
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    public String getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coremailbridge_mail.mid
     *
     * @param mid the value for coremailbridge_mail.mid
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    public void setMid(String mid) {
        this.mid = mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coremailbridge_mail.msid
     *
     * @return the value of coremailbridge_mail.msid
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    public String getMsid() {
        return msid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coremailbridge_mail.msid
     *
     * @param msid the value for coremailbridge_mail.msid
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    public void setMsid(String msid) {
        this.msid = msid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coremailbridge_mail.fid
     *
     * @return the value of coremailbridge_mail.fid
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    public String getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coremailbridge_mail.fid
     *
     * @param fid the value for coremailbridge_mail.fid
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    public void setFid(String fid) {
        this.fid = fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coremailbridge_mail.flag
     *
     * @return the value of coremailbridge_mail.flag
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    public String getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coremailbridge_mail.flag
     *
     * @param flag the value for coremailbridge_mail.flag
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    public void setFlag(String flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coremailbridge_mail.mail_from
     *
     * @return the value of coremailbridge_mail.mail_from
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    public String getMailFrom() {
        return mailFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coremailbridge_mail.mail_from
     *
     * @param mailFrom the value for coremailbridge_mail.mail_from
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    public void setMailFrom(String mailFrom) {
        this.mailFrom = mailFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coremailbridge_mail.mail_to
     *
     * @return the value of coremailbridge_mail.mail_to
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    public String getMailTo() {
        return mailTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coremailbridge_mail.mail_to
     *
     * @param mailTo the value for coremailbridge_mail.mail_to
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    public void setMailTo(String mailTo) {
        this.mailTo = mailTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coremailbridge_mail.size
     *
     * @return the value of coremailbridge_mail.size
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    public String getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coremailbridge_mail.size
     *
     * @param size the value for coremailbridge_mail.size
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    public void setSize(String size) {
        this.size = size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coremailbridge_mail.date
     *
     * @return the value of coremailbridge_mail.date
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coremailbridge_mail.date
     *
     * @param date the value for coremailbridge_mail.date
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    public void setDate(String date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coremailbridge_mail.pushed
     *
     * @return the value of coremailbridge_mail.pushed
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    public Boolean getPushed() {
        return pushed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coremailbridge_mail.pushed
     *
     * @param pushed the value for coremailbridge_mail.pushed
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    public void setPushed(Boolean pushed) {
        this.pushed = pushed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coremailbridge_mail.pushed_time
     *
     * @return the value of coremailbridge_mail.pushed_time
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    public Date getPushedTime() {
        return pushedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coremailbridge_mail.pushed_time
     *
     * @param pushedTime the value for coremailbridge_mail.pushed_time
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    public void setPushedTime(Date pushedTime) {
        this.pushedTime = pushedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coremailbridge_mail.receriver_id
     *
     * @return the value of coremailbridge_mail.receriver_id
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    public String getReceriverId() {
        return receriverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coremailbridge_mail.receriver_id
     *
     * @param receriverId the value for coremailbridge_mail.receriver_id
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    public void setReceriverId(String receriverId) {
        this.receriverId = receriverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coremailbridge_mail.msg_id
     *
     * @return the value of coremailbridge_mail.msg_id
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    public String getMsgId() {
        return msgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coremailbridge_mail.msg_id
     *
     * @param msgId the value for coremailbridge_mail.msg_id
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    public void setMsgId(String msgId) {
        this.msgId = msgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coremailbridge_mail.create_time
     *
     * @return the value of coremailbridge_mail.create_time
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coremailbridge_mail.create_time
     *
     * @param createTime the value for coremailbridge_mail.create_time
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coremailbridge_mail.update_time
     *
     * @return the value of coremailbridge_mail.update_time
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coremailbridge_mail.update_time
     *
     * @param updateTime the value for coremailbridge_mail.update_time
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coremailbridge_mail.subject
     *
     * @return the value of coremailbridge_mail.subject
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    public String getSubject() {
        return subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coremailbridge_mail.subject
     *
     * @param subject the value for coremailbridge_mail.subject
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    public void setSubject(String subject) {
        this.subject = subject;
    }
}