package com.hdsoft.coremailbridge.model;

import java.util.Date;

public class Matcher {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coremailbridge_matcher.id
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coremailbridge_matcher.name
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coremailbridge_matcher.role_info
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    private String roleInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coremailbridge_matcher.description
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coremailbridge_matcher.create_time
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coremailbridge_matcher.update_time
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coremailbridge_matcher.id
     *
     * @return the value of coremailbridge_matcher.id
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coremailbridge_matcher.id
     *
     * @param id the value for coremailbridge_matcher.id
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coremailbridge_matcher.name
     *
     * @return the value of coremailbridge_matcher.name
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coremailbridge_matcher.name
     *
     * @param name the value for coremailbridge_matcher.name
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coremailbridge_matcher.role_info
     *
     * @return the value of coremailbridge_matcher.role_info
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    public String getRoleInfo() {
        return roleInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coremailbridge_matcher.role_info
     *
     * @param roleInfo the value for coremailbridge_matcher.role_info
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    public void setRoleInfo(String roleInfo) {
        this.roleInfo = roleInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coremailbridge_matcher.description
     *
     * @return the value of coremailbridge_matcher.description
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coremailbridge_matcher.description
     *
     * @param description the value for coremailbridge_matcher.description
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coremailbridge_matcher.create_time
     *
     * @return the value of coremailbridge_matcher.create_time
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coremailbridge_matcher.create_time
     *
     * @param createTime the value for coremailbridge_matcher.create_time
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coremailbridge_matcher.update_time
     *
     * @return the value of coremailbridge_matcher.update_time
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coremailbridge_matcher.update_time
     *
     * @param updateTime the value for coremailbridge_matcher.update_time
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}