package com.hdsoft.coremailbridge.model;

public class Role {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coremailbridge_role.ROLE_ID
     *
     * @mbggenerated Sat Jan 19 09:51:17 CST 2019
     */
    private Long roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coremailbridge_role.ROLE_NAME
     *
     * @mbggenerated Sat Jan 19 09:51:17 CST 2019
     */
    private String roleName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coremailbridge_role.ROLE_ID
     *
     * @return the value of coremailbridge_role.ROLE_ID
     *
     * @mbggenerated Sat Jan 19 09:51:17 CST 2019
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coremailbridge_role.ROLE_ID
     *
     * @param roleId the value for coremailbridge_role.ROLE_ID
     *
     * @mbggenerated Sat Jan 19 09:51:17 CST 2019
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coremailbridge_role.ROLE_NAME
     *
     * @return the value of coremailbridge_role.ROLE_NAME
     *
     * @mbggenerated Sat Jan 19 09:51:17 CST 2019
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coremailbridge_role.ROLE_NAME
     *
     * @param roleName the value for coremailbridge_role.ROLE_NAME
     *
     * @mbggenerated Sat Jan 19 09:51:17 CST 2019
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }
}
