package com.hdsoft.coremailbridge.model;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coremailbridge_user.id
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coremailbridge_user.user_name
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coremailbridge_user.display_name
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    private String displayName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coremailbridge_user.password
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coremailbridge_user.email
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coremailbridge_user.mobile
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coremailbridge_user.fs_union_id
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    private String fsUnionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coremailbridge_user.status
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    private Boolean status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coremailbridge_user.create_time
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coremailbridge_user.update_time
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coremailbridge_user.id
     *
     * @return the value of coremailbridge_user.id
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coremailbridge_user.id
     *
     * @param id the value for coremailbridge_user.id
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coremailbridge_user.user_name
     *
     * @return the value of coremailbridge_user.user_name
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coremailbridge_user.user_name
     *
     * @param userName the value for coremailbridge_user.user_name
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coremailbridge_user.display_name
     *
     * @return the value of coremailbridge_user.display_name
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coremailbridge_user.display_name
     *
     * @param displayName the value for coremailbridge_user.display_name
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coremailbridge_user.password
     *
     * @return the value of coremailbridge_user.password
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coremailbridge_user.password
     *
     * @param password the value for coremailbridge_user.password
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coremailbridge_user.email
     *
     * @return the value of coremailbridge_user.email
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coremailbridge_user.email
     *
     * @param email the value for coremailbridge_user.email
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coremailbridge_user.mobile
     *
     * @return the value of coremailbridge_user.mobile
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coremailbridge_user.mobile
     *
     * @param mobile the value for coremailbridge_user.mobile
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coremailbridge_user.fs_union_id
     *
     * @return the value of coremailbridge_user.fs_union_id
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    public String getFsUnionId() {
        return fsUnionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coremailbridge_user.fs_union_id
     *
     * @param fsUnionId the value for coremailbridge_user.fs_union_id
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    public void setFsUnionId(String fsUnionId) {
        this.fsUnionId = fsUnionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coremailbridge_user.status
     *
     * @return the value of coremailbridge_user.status
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coremailbridge_user.status
     *
     * @param status the value for coremailbridge_user.status
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coremailbridge_user.create_time
     *
     * @return the value of coremailbridge_user.create_time
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coremailbridge_user.create_time
     *
     * @param createTime the value for coremailbridge_user.create_time
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coremailbridge_user.update_time
     *
     * @return the value of coremailbridge_user.update_time
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coremailbridge_user.update_time
     *
     * @param updateTime the value for coremailbridge_user.update_time
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}