package com.hdsoft.coremailbridge.model;

public class UserRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coremailbridge_user_role.ID
     *
     * @mbggenerated Sat Jan 19 09:51:17 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coremailbridge_user_role.USER_ID
     *
     * @mbggenerated Sat Jan 19 09:51:17 CST 2019
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coremailbridge_user_role.ROLE_ID
     *
     * @mbggenerated Sat Jan 19 09:51:17 CST 2019
     */
    private Long roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coremailbridge_user_role.ID
     *
     * @return the value of coremailbridge_user_role.ID
     *
     * @mbggenerated Sat Jan 19 09:51:17 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coremailbridge_user_role.ID
     *
     * @param id the value for coremailbridge_user_role.ID
     *
     * @mbggenerated Sat Jan 19 09:51:17 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coremailbridge_user_role.USER_ID
     *
     * @return the value of coremailbridge_user_role.USER_ID
     *
     * @mbggenerated Sat Jan 19 09:51:17 CST 2019
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coremailbridge_user_role.USER_ID
     *
     * @param userId the value for coremailbridge_user_role.USER_ID
     *
     * @mbggenerated Sat Jan 19 09:51:17 CST 2019
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coremailbridge_user_role.ROLE_ID
     *
     * @return the value of coremailbridge_user_role.ROLE_ID
     *
     * @mbggenerated Sat Jan 19 09:51:17 CST 2019
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coremailbridge_user_role.ROLE_ID
     *
     * @param roleId the value for coremailbridge_user_role.ROLE_ID
     *
     * @mbggenerated Sat Jan 19 09:51:17 CST 2019
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }
}
