package com.hdsoft.coremailbridge.model;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coremailbridge_user.id
     *
     * @mbggenerated Sat Jan 19 09:51:17 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coremailbridge_user.user_name
     *
     * @mbggenerated Sat Jan 19 09:51:17 CST 2019
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coremailbridge_user.display_name
     *
     * @mbggenerated Sat Jan 19 09:51:17 CST 2019
     */
    private String displayName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coremailbridge_user.password
     *
     * @mbggenerated Sat Jan 19 09:51:17 CST 2019
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coremailbridge_user.department_code
     *
     * @mbggenerated Sat Jan 19 09:51:17 CST 2019
     */
    private String departmentCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coremailbridge_user.nim_account
     *
     * @mbggenerated Sat Jan 19 09:51:17 CST 2019
     */
    private String nimAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coremailbridge_user.nim_token
     *
     * @mbggenerated Sat Jan 19 09:51:17 CST 2019
     */
    private String nimToken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coremailbridge_user.qs_account
     *
     * @mbggenerated Sat Jan 19 09:51:17 CST 2019
     */
    private String qsAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coremailbridge_user.create_time
     *
     * @mbggenerated Sat Jan 19 09:51:17 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coremailbridge_user.update_time
     *
     * @mbggenerated Sat Jan 19 09:51:17 CST 2019
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coremailbridge_user.id
     *
     * @return the value of coremailbridge_user.id
     *
     * @mbggenerated Sat Jan 19 09:51:17 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coremailbridge_user.id
     *
     * @param id the value for coremailbridge_user.id
     *
     * @mbggenerated Sat Jan 19 09:51:17 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coremailbridge_user.user_name
     *
     * @return the value of coremailbridge_user.user_name
     *
     * @mbggenerated Sat Jan 19 09:51:17 CST 2019
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coremailbridge_user.user_name
     *
     * @param userName the value for coremailbridge_user.user_name
     *
     * @mbggenerated Sat Jan 19 09:51:17 CST 2019
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coremailbridge_user.display_name
     *
     * @return the value of coremailbridge_user.display_name
     *
     * @mbggenerated Sat Jan 19 09:51:17 CST 2019
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coremailbridge_user.display_name
     *
     * @param displayName the value for coremailbridge_user.display_name
     *
     * @mbggenerated Sat Jan 19 09:51:17 CST 2019
     */
    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coremailbridge_user.password
     *
     * @return the value of coremailbridge_user.password
     *
     * @mbggenerated Sat Jan 19 09:51:17 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coremailbridge_user.password
     *
     * @param password the value for coremailbridge_user.password
     *
     * @mbggenerated Sat Jan 19 09:51:17 CST 2019
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coremailbridge_user.department_code
     *
     * @return the value of coremailbridge_user.department_code
     *
     * @mbggenerated Sat Jan 19 09:51:17 CST 2019
     */
    public String getDepartmentCode() {
        return departmentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coremailbridge_user.department_code
     *
     * @param departmentCode the value for coremailbridge_user.department_code
     *
     * @mbggenerated Sat Jan 19 09:51:17 CST 2019
     */
    public void setDepartmentCode(String departmentCode) {
        this.departmentCode = departmentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coremailbridge_user.nim_account
     *
     * @return the value of coremailbridge_user.nim_account
     *
     * @mbggenerated Sat Jan 19 09:51:17 CST 2019
     */
    public String getNimAccount() {
        return nimAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coremailbridge_user.nim_account
     *
     * @param nimAccount the value for coremailbridge_user.nim_account
     *
     * @mbggenerated Sat Jan 19 09:51:17 CST 2019
     */
    public void setNimAccount(String nimAccount) {
        this.nimAccount = nimAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coremailbridge_user.nim_token
     *
     * @return the value of coremailbridge_user.nim_token
     *
     * @mbggenerated Sat Jan 19 09:51:17 CST 2019
     */
    public String getNimToken() {
        return nimToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coremailbridge_user.nim_token
     *
     * @param nimToken the value for coremailbridge_user.nim_token
     *
     * @mbggenerated Sat Jan 19 09:51:17 CST 2019
     */
    public void setNimToken(String nimToken) {
        this.nimToken = nimToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coremailbridge_user.qs_account
     *
     * @return the value of coremailbridge_user.qs_account
     *
     * @mbggenerated Sat Jan 19 09:51:17 CST 2019
     */
    public String getQsAccount() {
        return qsAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coremailbridge_user.qs_account
     *
     * @param qsAccount the value for coremailbridge_user.qs_account
     *
     * @mbggenerated Sat Jan 19 09:51:17 CST 2019
     */
    public void setQsAccount(String qsAccount) {
        this.qsAccount = qsAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coremailbridge_user.create_time
     *
     * @return the value of coremailbridge_user.create_time
     *
     * @mbggenerated Sat Jan 19 09:51:17 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coremailbridge_user.create_time
     *
     * @param createTime the value for coremailbridge_user.create_time
     *
     * @mbggenerated Sat Jan 19 09:51:17 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coremailbridge_user.update_time
     *
     * @return the value of coremailbridge_user.update_time
     *
     * @mbggenerated Sat Jan 19 09:51:17 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coremailbridge_user.update_time
     *
     * @param updateTime the value for coremailbridge_user.update_time
     *
     * @mbggenerated Sat Jan 19 09:51:17 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}
