
package com.hdsoft.coremailbridge.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "API", targetNamespace = "http://coremail.cn/apiws", wsdlLocation = "http://116.198.25.145:9900/apiws/services/API?wsdl")
public class API_Service
    extends Service
{

    private final static URL API_WSDL_LOCATION;
    private final static WebServiceException API_EXCEPTION;
    private final static QName API_QNAME = new QName("http://coremail.cn/apiws", "API");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://116.198.25.145:9900/apiws/services/API?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        API_WSDL_LOCATION = url;
        API_EXCEPTION = e;
    }

    public API_Service() {
        super(__getWsdlLocation(), API_QNAME);
    }

    public API_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), API_QNAME, features);
    }

    public API_Service(URL wsdlLocation) {
        super(wsdlLocation, API_QNAME);
    }

    public API_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, API_QNAME, features);
    }

    public API_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public API_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns API
     */
    @WebEndpoint(name = "APIPort")
    public API getAPIPort() {
        return super.getPort(new QName("http://coremail.cn/apiws", "APIPort"), API.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns API
     */
    @WebEndpoint(name = "APIPort")
    public API getAPIPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://coremail.cn/apiws", "APIPort"), API.class, features);
    }

    private static URL __getWsdlLocation() {
        if (API_EXCEPTION!= null) {
            throw API_EXCEPTION;
        }
        return API_WSDL_LOCATION;
    }

}
