package com.hdsoft.coremailbridge.persistence;

import com.hdsoft.coremailbridge.model.Matcher;
import com.hdsoft.coremailbridge.model.MatcherExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MatcherMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coremailbridge_matcher
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    int countByExample(MatcherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coremailbridge_matcher
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    int deleteByExample(MatcherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coremailbridge_matcher
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coremailbridge_matcher
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    int insert(Matcher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coremailbridge_matcher
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    int insertSelective(Matcher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coremailbridge_matcher
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    List<Matcher> selectByExample(MatcherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coremailbridge_matcher
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    Matcher selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coremailbridge_matcher
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    int updateByExampleSelective(@Param("record") Matcher record, @Param("example") MatcherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coremailbridge_matcher
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    int updateByExample(@Param("record") Matcher record, @Param("example") MatcherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coremailbridge_matcher
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    int updateByPrimaryKeySelective(Matcher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coremailbridge_matcher
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    int updateByPrimaryKey(Matcher record);
}