package com.hdsoft.coremailbridge.persistence;

import java.util.List;

import com.hdsoft.coremailbridge.model.Matcher;
import com.hdsoft.coremailbridge.model.MatcherExample;
import org.apache.ibatis.annotations.Param;

public interface MatcherMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coremailbridge_matcher
     *
     * @mbggenerated Sat Jan 19 09:51:17 CST 2019
     */
    int countByExample(MatcherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coremailbridge_matcher
     *
     * @mbggenerated Sat Jan 19 09:51:17 CST 2019
     */
    int deleteByExample(MatcherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coremailbridge_matcher
     *
     * @mbggenerated Sat Jan 19 09:51:17 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coremailbridge_matcher
     *
     * @mbggenerated Sat Jan 19 09:51:17 CST 2019
     */
    int insert(Matcher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coremailbridge_matcher
     *
     * @mbggenerated Sat Jan 19 09:51:17 CST 2019
     */
    int insertSelective(Matcher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coremailbridge_matcher
     *
     * @mbggenerated Sat Jan 19 09:51:17 CST 2019
     */
    List<Matcher> selectByExample(MatcherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coremailbridge_matcher
     *
     * @mbggenerated Sat Jan 19 09:51:17 CST 2019
     */
    Matcher selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coremailbridge_matcher
     *
     * @mbggenerated Sat Jan 19 09:51:17 CST 2019
     */
    int updateByExampleSelective(@Param("record") Matcher record, @Param("example") MatcherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coremailbridge_matcher
     *
     * @mbggenerated Sat Jan 19 09:51:17 CST 2019
     */
    int updateByExample(@Param("record") Matcher record, @Param("example") MatcherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coremailbridge_matcher
     *
     * @mbggenerated Sat Jan 19 09:51:17 CST 2019
     */
    int updateByPrimaryKeySelective(Matcher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coremailbridge_matcher
     *
     * @mbggenerated Sat Jan 19 09:51:17 CST 2019
     */
    int updateByPrimaryKey(Matcher record);
}
