package com.hdsoft.coremailbridge.persistence;

import java.util.List;

import com.hdsoft.coremailbridge.model.Role;
import com.hdsoft.coremailbridge.model.RoleExample;
import org.apache.ibatis.annotations.Param;

public interface RoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coremailbridge_role
     *
     * @mbggenerated Sat Jan 19 09:51:17 CST 2019
     */
    int countByExample(RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coremailbridge_role
     *
     * @mbggenerated Sat Jan 19 09:51:17 CST 2019
     */
    int deleteByExample(RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coremailbridge_role
     *
     * @mbggenerated Sat Jan 19 09:51:17 CST 2019
     */
    int deleteByPrimaryKey(Long roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coremailbridge_role
     *
     * @mbggenerated Sat Jan 19 09:51:17 CST 2019
     */
    int insert(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coremailbridge_role
     *
     * @mbggenerated Sat Jan 19 09:51:17 CST 2019
     */
    int insertSelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coremailbridge_role
     *
     * @mbggenerated Sat Jan 19 09:51:17 CST 2019
     */
    List<Role> selectByExample(RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coremailbridge_role
     *
     * @mbggenerated Sat Jan 19 09:51:17 CST 2019
     */
    Role selectByPrimaryKey(Long roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coremailbridge_role
     *
     * @mbggenerated Sat Jan 19 09:51:17 CST 2019
     */
    int updateByExampleSelective(@Param("record") Role record, @Param("example") RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coremailbridge_role
     *
     * @mbggenerated Sat Jan 19 09:51:17 CST 2019
     */
    int updateByExample(@Param("record") Role record, @Param("example") RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coremailbridge_role
     *
     * @mbggenerated Sat Jan 19 09:51:17 CST 2019
     */
    int updateByPrimaryKeySelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coremailbridge_role
     *
     * @mbggenerated Sat Jan 19 09:51:17 CST 2019
     */
    int updateByPrimaryKey(Role record);
}
