package com.hdsoft.coremailbridge.persistence;

import com.hdsoft.coremailbridge.model.Role;
import com.hdsoft.coremailbridge.model.RoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coremailbridge_role
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    int countByExample(RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coremailbridge_role
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    int deleteByExample(RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coremailbridge_role
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    int deleteByPrimaryKey(Long roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coremailbridge_role
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    int insert(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coremailbridge_role
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    int insertSelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coremailbridge_role
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    List<Role> selectByExample(RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coremailbridge_role
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    Role selectByPrimaryKey(Long roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coremailbridge_role
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    int updateByExampleSelective(@Param("record") Role record, @Param("example") RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coremailbridge_role
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    int updateByExample(@Param("record") Role record, @Param("example") RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coremailbridge_role
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    int updateByPrimaryKeySelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coremailbridge_role
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    int updateByPrimaryKey(Role record);
}