package com.hdsoft.coremailbridge.persistence;

import com.hdsoft.coremailbridge.model.User;
import com.hdsoft.coremailbridge.model.UserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coremailbridge_user
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    int countByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coremailbridge_user
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    int deleteByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coremailbridge_user
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coremailbridge_user
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coremailbridge_user
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coremailbridge_user
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    List<User> selectByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coremailbridge_user
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    User selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coremailbridge_user
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    int updateByExampleSelective(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coremailbridge_user
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    int updateByExample(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coremailbridge_user
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coremailbridge_user
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    int updateByPrimaryKey(User record);
}