package com.hdsoft.coremailbridge.persistence;

import com.hdsoft.coremailbridge.model.UserRole;
import com.hdsoft.coremailbridge.model.UserRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coremailbridge_user_role
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    int countByExample(UserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coremailbridge_user_role
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    int deleteByExample(UserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coremailbridge_user_role
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coremailbridge_user_role
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    int insert(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coremailbridge_user_role
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    int insertSelective(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coremailbridge_user_role
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    List<UserRole> selectByExample(UserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coremailbridge_user_role
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    UserRole selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coremailbridge_user_role
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    int updateByExampleSelective(@Param("record") UserRole record, @Param("example") UserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coremailbridge_user_role
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    int updateByExample(@Param("record") UserRole record, @Param("example") UserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coremailbridge_user_role
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    int updateByPrimaryKeySelective(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coremailbridge_user_role
     *
     * @mbggenerated Sun Oct 16 17:21:00 CST 2022
     */
    int updateByPrimaryKey(UserRole record);
}