package com.hdsoft.coremailbridge.persistence;

import java.util.List;

import com.hdsoft.coremailbridge.model.UserRole;
import com.hdsoft.coremailbridge.model.UserRoleExample;
import org.apache.ibatis.annotations.Param;

public interface UserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coremailbridge_user_role
     *
     * @mbggenerated Sat Jan 19 09:51:17 CST 2019
     */
    int countByExample(UserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coremailbridge_user_role
     *
     * @mbggenerated Sat Jan 19 09:51:17 CST 2019
     */
    int deleteByExample(UserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coremailbridge_user_role
     *
     * @mbggenerated Sat Jan 19 09:51:17 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coremailbridge_user_role
     *
     * @mbggenerated Sat Jan 19 09:51:17 CST 2019
     */
    int insert(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coremailbridge_user_role
     *
     * @mbggenerated Sat Jan 19 09:51:17 CST 2019
     */
    int insertSelective(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coremailbridge_user_role
     *
     * @mbggenerated Sat Jan 19 09:51:17 CST 2019
     */
    List<UserRole> selectByExample(UserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coremailbridge_user_role
     *
     * @mbggenerated Sat Jan 19 09:51:17 CST 2019
     */
    UserRole selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coremailbridge_user_role
     *
     * @mbggenerated Sat Jan 19 09:51:17 CST 2019
     */
    int updateByExampleSelective(@Param("record") UserRole record, @Param("example") UserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coremailbridge_user_role
     *
     * @mbggenerated Sat Jan 19 09:51:17 CST 2019
     */
    int updateByExample(@Param("record") UserRole record, @Param("example") UserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coremailbridge_user_role
     *
     * @mbggenerated Sat Jan 19 09:51:17 CST 2019
     */
    int updateByPrimaryKeySelective(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coremailbridge_user_role
     *
     * @mbggenerated Sat Jan 19 09:51:17 CST 2019
     */
    int updateByPrimaryKey(UserRole record);
}
